
# Makefile for Coq Proof Verification - Generated by build.sh proof
# Enhanced for clarity and dynamic proof file handling

COQBIN?=coqbin
COQ_FLAGS?=
COQC_OPTIMIZATION?=-native-compiler yes # Default optimization flag

PROOF_DIR=proofs
METAMORPHIC_Q_FLAG=-Q . Metamorphic
PROOF_Q_FLAG=-Q $(PROOF_DIR) Metamorphic

# Dynamically find all .v files in the proofs directory
COQMF_THEORIES_V_FILES := $(shell find src/core/verification/proofs -name "*.v")
MAINFILE := $(patsubst src/core/verification/proofs/%.v,Metamorphic.%,$(COQMF_THEORIES_V_FILES))

COQ_VERSIONS_FLAGS = -compat v8.5 -compat v8.6 -compat v8.7 -compat v8.8 -compat v8.9 -compat v8.10 -compat v8.11 -compat v8.12 -compat v8.13 -compat v8.14 -compat v8.15 -compat v8.16 -compat v8.17 -compat v9.0

DEFAULT_TARGET=opt
export DEFAULT_TARGET

include $(COQBIN)/coq_makefile.conf

# Coq Makefile Targets

byte: $(addsuffix .byte, $(MAINFILE))
opt: $(addsuffix .opt, $(MAINFILE))
native: opt

%.byte: %.vo
	$(COQC) $(COQ_FLAGS) -byte -o $@ $<

%.opt: %.vo
	$(COQC) $(COQ_FLAGS) $(COQC_OPTIMIZATION) -o $@ $<

%.vo: %.v
	$(COQC) $(COQ_FLAGS) -q -vo $@ $<

coq-verify: opt
	@echo "-== Coq Proof Verification Started =="
	@$(MAKE) -f Makefile opt || { # Improved error handling: Fail fast and report error
		echo "::error:: Coq Proof Verification Failed! See console output for details."
		exit 1
	}
	@echo "-== Coq Proof Verification Completed Successfully =="

coq-edit: MODULE ?= BoundaryDetectionProofs # Default module if MODULE not specified
	@echo "Starting CoqIDE for module: $(MODULE)"
	coqide -load-path "$(PROOF_DIR)" -load-path "." "$(PROOF_DIR)/$(MODULE).v"

coq-coverage:
	@echo "-== Generating Coq Coverage Report =="
	coqwc -html coverage_report $(PROOF_DIR)/*.v # Coverage for all proof files
	@echo "-== Coq Coverage Report Generated (coverage_report.html) =="

clean:
	rm -f *.byte *.opt *.vo *.v.d *.glob *.aux *.log Makefile proof-overview.svg coverage_report.html

-include Makefile.conf



